# Generated by Django 2.2.6 on 2019-10-23 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('icon', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('icon', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('size', models.DecimalField(decimal_places=1, max_digits=3)),
                ('status', models.CharField(max_length=1)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scrum_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackTrack.Manager')),
            ],
        ),
        migrations.CreateModel(
            name='SprintBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_number', models.CharField(max_length=4)),
                ('estimated_time', models.DecimalField(decimal_places=2, max_digits=3)),
                ('time_spent', models.DecimalField(decimal_places=2, max_digits=3)),
                ('pbi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackTrack.ProductBacklog')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackTrack.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_to_do', models.CharField(max_length=200)),
                ('time', models.DecimalField(decimal_places=2, max_digits=3)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackTrack.Developer')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackTrack.SprintBacklog')),
            ],
        ),
        migrations.AddField(
            model_name='productbacklog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackTrack.Project'),
        ),
        migrations.AddField(
            model_name='developer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackTrack.Project'),
        ),
    ]
