# Generated by Django 2.2.6 on 2019-10-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackTrack', '0002_auto_20191023_1855'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='developer',
            constraint=models.UniqueConstraint(fields=('username',), name='unqiue developer username'),
        ),
        migrations.AddConstraint(
            model_name='manager',
            constraint=models.UniqueConstraint(fields=('username',), name='unique manager username'),
        ),
        migrations.AddConstraint(
            model_name='productbacklog',
            constraint=models.UniqueConstraint(fields=('name',), name='unqiue pbi'),
        ),
        migrations.AddConstraint(
            model_name='productbacklog',
            constraint=models.UniqueConstraint(fields=('order',), name='unique order'),
        ),
    ]
