# Generated by Django 2.2.6 on 2019-10-23 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackTrack', '0003_auto_20191023_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='product_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProductOwner', to='BackTrack.Developer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='developer',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='BackTrack.Project'),
        ),
    ]
