# Generated by Django 2.2.6 on 2019-10-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackTrack', '0004_auto_20191023_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='product_owner',
        ),
    ]
