# Generated by Django 2.2.6 on 2019-10-23 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackTrack', '0005_remove_project_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='product_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ProductOwner', to='BackTrack.Developer'),
            preserve_default=False,
        ),
    ]
