# Generated by Django 2.2.6 on 2019-10-28 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackTrack', '0007_productbacklog_sprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbacklog',
            name='sprint',
        ),
        migrations.RemoveField(
            model_name='sprintbacklog',
            name='project',
        ),
        migrations.RemoveField(
            model_name='sprintbacklog',
            name='sprint_number',
        ),
        migrations.AddField(
            model_name='productbacklog',
            name='sprintbacklog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprintbacklog', to='BackTrack.SprintBacklog'),
        ),
        migrations.AddField(
            model_name='project',
            name='current_sprint_number',
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sprintbacklog',
            name='pbi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pbi', to='BackTrack.ProductBacklog'),
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_number', models.CharField(max_length=4)),
                ('capacity', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project2', to='BackTrack.Project')),
            ],
        ),
        migrations.AddField(
            model_name='sprintbacklog',
            name='sprint',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sprint', to='BackTrack.Sprint'),
            preserve_default=False,
        ),
    ]
